name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write

env:
  GH_TOKEN: ${{ github.token }}
  SYSTEMC_HOME: ./systemc
  LD_LIBRARY_PATH: ./systemc/lib
  TEST_BUILD: yes

jobs:

  deps:

    name: Dependency checks
    runs-on: ubuntu-latest

    steps:

      - name: Set up build tools
        run: sudo apt-get install -y build-essential

      - name: Set up libs
        id: cache-libs
        uses: actions/cache/restore@v3
        with:
          path: ./systemc
          key: libs

      - if: ${{ steps.cache-libs.outputs.cache-hit != 'true' }}
        name: Build libs
        run: |
          git clone https://github.com/simplifieduser/systemc.git
          cd systemc
          make
          cd ..

      - if: ${{ steps.cache-libs.outputs.cache-hit != 'true' }}
        name: Cache libs
        uses: actions/cache/save@v3
        with:
          path: ./systemc
          key: libs

  lint:

    name: Linting checks
    runs-on: ubuntu-latest
    needs: deps

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build tools
        run: sudo apt-get install -y build-essential

      - name: Set up libs
        id: cache-libs
        uses: actions/cache/restore@v3
        with:
          path: ./systemc
          key: libs

      - name: Run linter
        run: make tidy -k


  build:

    name: Build check
    runs-on: ubuntu-latest
    needs: deps

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build tools
        run: sudo apt-get install -y build-essential

      - name: Set up libs
        uses: actions/cache/restore@v3
        with:
          path: ./systemc
          key: libs

      - name: Build project
        run: make debug

      - name: Clear build cache
        continue-on-error: true
        run: gh cache delete build

      - name: Cache build
        uses: actions/cache/save@v3
        with:
          path: ./dist
          key: build

  test:
    name: Test case checks
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pytest
        run: pip install pytest

      - name: Set up libs
        uses: actions/cache/restore@v3
        with:
          path: ./systemc
          key: libs

      - name: Restore cached build
        uses: actions/cache/restore@v3
        with:
          path: ./dist
          key: build

      - name: Run tests with pytest
        run: |
          sudo chmod +x ./dist/r5mm
          pytest