name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SYSTEMC_HOME: ./systemc
  LD_LIBRARY_PATH: ./systemc/lib

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build tools
        run: sudo apt-get install -y build-essential

      - name: Run code linter
        run: make tidy

  build:
    runs-on: ubuntu-latest
    needs: build-deps

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build tools
        run: sudo apt-get install -y build-essential

      - name: Set up libs
        id: cache-libs
        uses: actions/cache@v3
        with:
          path: ./systemc
          restore-keys: libs

      - if: ${{ steps.cache-libs.outputs.cache-hit != 'true' }}
        name: Build libs
        run: |
          git clone https://github.com/simplifieduser/systemc.git
          cd systemc
          make
          cd ..

      - if: ${{ steps.cache-libs.outputs.cache-hit != 'true' }}
        name: Cache libs
        uses: actions/cache@v3
        with:
          path: ./systemc
          key: libs

      - name: Build project
        run: make debug

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ./dist
          key: build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pytest
        run: pip install pytest

      - name: Copy cached build
        uses: actions/cache@v3
        with:
          path: ./dist
          key: build

      - name: Run tests with pytest
        run: |
          sudo chmod +x ./dist/r5mm
          pytest