name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SYSTEMC_HOME: ./systemc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build tools
        run: sudo apt-get install -y build-essential

      - name: Set up build libs
        uses: actions/checkout@v2
        with:
          repository: 'simplifieduser/systemc'
          path: 'systemc'

      - name: Build libs
        run: |
          cd ./systemc
          make
          cd ..

      - name: Build project
        run: make

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ./dist
          key: build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install pytest
        run: pip install pytest

      - name: Copy cached build
        uses: actions/cache@v3
        with:
          path: ./dist
          key: build

      - name: Run tests with pytest
        run: |
          sudo chmod +x ./dist/r5mm
          pytest